FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt xgboost joblib

COPY training/train_model.py /app/
COPY feature_engineering/feature_repo /feature_repo/

ENTRYPOINT ["python", "train_model.py"]